#!/bin/bash
#SBATCH --time=00:1:00        # Walltime in hh:mm:ss
#SBATCH --nodes=4    # Number of nodes
#SBATCH --ntasks-per-node=1   # Number of MPI ranks per node
#SBATCH --cpus-per-task=128      # Number of OpenMP threads for each MPI process/rank
#SBATCH --gres=gpu:4            # gpu
#SBATCH --mem-per-cpu=1800
#SBATCH --account=cin_HPCqe  
#SBATCH --partition=m100_usr_prod
#SBATCH --err=error.txt
#SBATCH --job-name=un1b
module load profile/advanced 
module load gnu
module load hpc-sdk
module load blas 
module load cuda
make temporal  WHICH=mmul4unb NAME=ZMPLX >> Imaketest.txt 2>&1
