#!/bin/bash
#SBATCH --time=10:00:00        # Walltime in hh:mm:ss
#SBATCH --nodes=4    # Number of nodes
#SBATCH --ntasks-per-node=1   # Number of MPI ranks per node
#SBATCH --cpus-per-task=128      # Number of OpenMP threads for each MPI process/rank
#SBATCH --gres=gpu:4            # gpu
#SBATCH --mem-per-cpu=1800
#SBATCH --account=cin_HPCqe  
#SBATCH --partition=m100_usr_prod
#SBATCH --err=error.txt
#SBATCH --job-name=qrh24
module load profile/advanced 
module load gnu
module load hpc-sdk
module load blas 


module load cuda/10.1 
mpirun -np 4 -host $SLURM_JOB_NODELIST ./bin/testabsoZMPLX 2 2 1  > ./out/testabsoseries.out
